# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f83cd90c6d2db7f017ddefcb5edabee7f701ea11574ffdd64a25f183beb04f5a5f014ddd8fd9a0a5350aad21e1ed250c62b35f1fb53decc603f0d1bb19d59c6d

test:
  secret_key_base: 2ae008401471a406ac04cb1ab93e6e695292ccace02a0c5b48f4aea90deaf109b28ce4e3c4e968d83aebac132966f90e2c08416662a32da347732f587ee036e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
